### PR TITLE
Fix opacity under filter

### PR DESCRIPTION
**Pull request by Happypig375**
Ignoring attributes is only for background image, doing this for the source image should be incorrect implementation.

### CODE REVIEW

**Comment by wieslawsoltes** [comment]
@Happypig375 Can you just include filter fix in this PR?

**Comment by Happypig375** [comment]
@wieslawsoltes This depends on the previous PR.

**Comment by Happypig375** [comment]
After merging the previous one, the diff should be minimised automatically,

**Comment by wieslawsoltes** [comment]
Could please remove leftover image tests/Tests using SvgToPng/Sign in.png ?

**Comment by wieslawsoltes** [comment]
> Could please remove leftover image tests/Tests using SvgToPng/Sign in.png ?

@Happypig375 reverted

**Review by wieslawsoltes — APPROVED** [review]

**Pull request merged**
